# Generated by Django 4.2.11 on 2024-03-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LottoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottogroup', models.CharField(blank=True, db_column='LOTTOGROUP', max_length=255)),
                ('odd_cnt', models.IntegerField(blank=True, db_column='ODD_CNT', null=True)),
                ('small_cnt', models.IntegerField(blank=True, db_column='SMALL_CNT', null=True)),
                ('prime_cnt', models.IntegerField(blank=True, db_column='PRIME_CNT', null=True)),
                ('consq_cnt', models.IntegerField(blank=True, db_column='CONSQ_CNT', null=True)),
            ],
            options={
                'db_table': 'lotto_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LottoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(blank=True, db_column='round')),
                ('num1', models.IntegerField(blank=True, db_column='num1', null=True)),
                ('num2', models.IntegerField(blank=True, db_column='num2', null=True)),
                ('num3', models.IntegerField(blank=True, db_column='num3', null=True)),
                ('num5', models.IntegerField(blank=True, db_column='num5', null=True)),
                ('num6', models.IntegerField(blank=True, db_column='num6', null=True)),
            ],
            options={
                'db_table': 'lotto_result',
                'managed': False,
            },
        ),
    ]
